version: '3'
services:
  app:
    image: 'kube:latest'
    build:
      context: .
    container_name: app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/kube
    ports:
       - 8080:8080
    restart: always
    links:
      - db
  db:
      image: 'postgres:11-alpine'
      container_name: db
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=kube
        - PGDATA=/tmp
      ports:
        - 5432:5432
      volumes:
          - d:/gitTest:/var/lib/postgresql/data
      restart: always

